[tool.black]
line-length=87

[tool.isort]
line_length=87  # intentionally shorter than `black` and `flake8`
atomic=true
force_grid_wrap=0
include_trailing_comma=true
lines_after_imports=2
lines_between_types=0
multi_line_output=3
not_skip="__init__.py"
use_parentheses=true

[tool.bandit]
targets = ["src"]
skips = ["B101", "B608", "B108"]
